-- PL/SQL code to create a calculator
 
DECLARE	
	NUM1 NUMBER;
	NUM2 NUMBER;
	RES NUMBER;
	I NUMBER;
	CONT NUMBER:=1;
BEGIN	
	NUM1:=&NUM1;
	NUM2:=&NUM2;
	DBMS_OUTPUT.PUT_LINE('ENTER CHOICE : 1[ADDITION] 2[SUBTRACTION] 3[MULTIPLICATION] 4[DIVISION] 5[MODULUS]');
	I:=&I;
	CASE I
		WHEN 1 THEN RES:=NUM1+NUM2;
		WHEN 2 THEN RES:=NUM1-NUM2;
		WHEN 3 THEN RES:=NUM1*NUM2;
		WHEN 4 THEN RES:=NUM1/NUM2;
		WHEN 5 THEN RES:= MOD(NUM1,NUM2);
		ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH CHOICE');
	END CASE;
	DBMS_OUTPUT.PUT_LINE('RESULT IS '||RES||'');
END;
/